# Generated by Django 2.2.1 on 2019-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='tianmao url')),
                ('title', models.CharField(max_length=255, verbose_name='天猫产品标题')),
                ('subtitle', models.CharField(max_length=128, verbose_name='天猫产品副标题')),
                ('colors', models.CharField(max_length=128, verbose_name='天猫产品颜色')),
                ('sku', models.CharField(max_length=36, verbose_name='货号')),
                ('sizes', models.CharField(max_length=128, verbose_name='尺寸')),
                ('status', models.CharField(choices=[('done', '完成'), ('going', '正在进行'), ('todo', '未开始')], default='todo', max_length=12, verbose_name='状态')),
                ('brand_id', models.PositiveIntegerField(db_index=True, verbose_name='品牌编号')),
            ],
            options={
                'verbose_name': 'sparrow crawl product',
                'verbose_name_plural': 'sparrow crawl products',
                'db_table': 'sparrow_crawl_product',
            },
        ),
    ]
