# Generated by Django 2.2.1 on 2019-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlproduct',
            name='colors',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='天猫产品颜色'),
        ),
        migrations.AlterField(
            model_name='crawlproduct',
            name='sizes',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='尺寸'),
        ),
    ]
