# Generated by Django 2.2.1 on 2019-08-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_crawltask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlproduct',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='天猫产品颜色'),
        ),
    ]
