# Generated by Django 2.2.1 on 2019-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0005_auto_20190827_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawltask',
            name='url',
            field=models.CharField(max_length=255, verbose_name='tianmao url'),
        ),
    ]
